### ISSUE TITLE
Feature request: disable chat 'debug' messages

### ISSUE THREAD

**Issue by raptormama** [solagegrey/ElvUI_ItemCount#3]
If the user wishes to simply use the DataText display to monitor item count, the chatbox messages may be redundant.

If an item is 'silent', do not print item-gained/goal-reached messages to chat. Alternatively, provide a check box to disable these messages.

**Comment by solagegrey** [comment]
Thanks for using ElvUI_ItemCount, and for contributing to the conversation. If you're getting a whole lot of debug messages, you may have an older version of the addon installed, one that snuck through where the 'AllowDebug' setting is set to 'true'. Please make sure you have the latest version, which won't barf all over the chat box.

Regardless of the above, I will work on a config toggle that disables all output to the chat box, and thank you for the suggestion! A new version should be ready within a day or two.

**Comment by raptormama** [comment]
Thanks! I got my copy from tukui,org/WoWUp.

For now, I wrapped the debug statements in `if not cObj.Silent then (...) end` statements and that seems to have done the trick.

Aside: Finding alt-rightclick code commented out answered why that never worked for me, but dragging the tracked item from my bag to the input box did - perfectly.

**Comment by solagegrey** [comment]
The debug statements should not be reached at all by running code, because at the top of the file you should see
`local AllowDebug = false`

If you look at the debugSay function, the output is already wrapped with 
`if AllowDebug and pf.Debug then ... end`

When AllowDebug is True, a config toggle will appear to allow showing/not showing the debug messages.

The latest version is 2.0.39, and was distributed with AllowDebug = false.
